---
- name: Configure Linux Workloads
  hosts: linux_workload
  become: true
  vars:
    user_home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Copy Demo Server.sh 
      copy:
        src: "server.sh"
        dest: "/home/{{ ansible_user }}/"
        mode: '0777'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      

    - name: Copy VM instance data file
      copy:
        src: vm-instance-data.txt
        dest: "/home/{{ ansible_user }}/vm-instance-data.txt"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"